/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1
 Source Server Type    : MySQL
 Source Server Version : 50562
 Source Host           : localhost:3306
 Source Schema         : mangos

 Target Server Type    : MySQL
 Target Server Version : 50562
 File Encoding         : 65001

 Date: 06/05/2022 17:24:58
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for quest_greeting
-- ----------------------------
DROP TABLE IF EXISTS `quest_greeting`;
CREATE TABLE `quest_greeting`  (
  `entry` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `type` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `content_default` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `content_loc1` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc2` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc3` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc4` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc5` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc6` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc7` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `content_loc8` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `emote_id` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `emote_delay` int(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`entry`, `type`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of quest_greeting
-- ----------------------------
INSERT INTO `quest_greeting` VALUES (823, 0, 'Hello there, $c.  Normally I\'d be out on the beat looking after the folk of Stormwind, but a lot of the Stormwind guards are fighting in the other lands.  So here I am, deputized and offering bounties when I\'d rather be on patrol...', NULL, NULL, 'Guten Tag, $C. Normalerweise würde ich jetzt meine Runde machen und die Leute von Sturmwind beschützen, doch viele der Wachen von Sturmwind kämpfen in fremden Landen. Daher mache ich jetzt hier Vertretung und setze Kopfgelder aus, wo ich doch eigentlich lieber auf Patrouille sein würde...', NULL, NULL, 'Hola, $c. Normalmente estaría en el ritmo cuidando a la gente de Ventormenta, pero muchos de los guardias de Ventormenta están luchando en las otras tierras. Así que aquí estoy, suplente y ofreciendo recompensas cuando prefiero estar de patrulla ...', NULL, 'Приветствую тебя, $c. Обычно я присматриваю за народом Штормграда, но в это тяжелое время, многие наши стражники ушли на сражения в другие края. И вот теперь, вместо того чтобы вести патруль, я как заместитель, предлагаю вознаграждение за оказанную помощь...', 1, 0);
INSERT INTO `quest_greeting` VALUES (241, 0, 'Hey there, friend.  My name\'s Remy.$BI\'m from Redridge to the east, and came here looking for business, looking for business.  You got any...got any??', NULL, NULL, 'He, mein Freund. Man nennt mich Remy. Ich komme aus dem Rotkammgebirge im Osten und bin auf der Suche nach interessanten... Geschäften. Interessanten... Geschäften. Habt Ihr vielleicht welche... vielleicht welche?', NULL, NULL, 'Hola, amigo. Mi nombre es Remy. $BSoy de Creata Roja, al este, y vine aquí buscando negocios, buscando negocios. ¿Tienes alguna ... tienes alguna?', NULL, 'Послушай $gприятель:приятельница;. Меня зовут Реми.$BЯ с востока Красногорья, а сюда пришел за делом, да, за делом. У тебя не найдется дела? Не найдется?', 0, 0);
INSERT INTO `quest_greeting` VALUES (261, 0, 'Hello, citizen.  You look like a $g man : woman; with a purpose - do you have business with the Stormwind Army?', NULL, NULL, 'Seid gegrüßt. Ihr seht aus wie ein $g Mann : Frau;, der weiß, was er will... habt ihr mit der Armee von Sturmwind zu tun?', NULL, NULL, 'Hola, ciudadano. Pareces $g un hombre : una mujer; con un propósito: ¿tienes negocios con el ejército de Ventormenta?', NULL, 'Приветствую, $gгражданин:гражданка;. Ты не выглядишь $gпраздным:праздной; зевакой. Что за дело привело тебя в армию Штормграда?', 0, 0);
INSERT INTO `quest_greeting` VALUES (237, 0, 'Nothing but trouble in these parts.  I tried to tell that fool Saldean to get out while he still could but he won\'t hear of it.  But I ain\'t no fool.  Verna and I are gonna mosey on out as soon as we get this wagon fixed.', NULL, NULL, 'In dieser Gegend gibt es wirklich nichts als Arger. Ich habe versucht, den Dummkopf Saldean dazu zu bringen, sich aus dem Staub zu machen, solange das noch geht, aber er will einfach nicht hören. Aber ich bin kein Dummkopf. Verna und ich hauen ab, sobald wir diesen Wagen repariert haben.', NULL, NULL, 'Nada más que problemas en estas partes. Traté de decirle a ese tonto de Saldean que salga mientras aún pueda, pero no quiere saberlo. Pero no soy tonto. Verna y yo saldremos tan pronto como arreglemos este vagón.', NULL, 'В этих краях нет ничего кроме неприятностей. Я пытался сказать этому глупцу Сальдену чтобы он уходил пока может, но он не хотел и слышать об этом. Но я не глупец, как только мы с Верной починим эту повозку, сразу уедем отсюда.', 0, 0);
INSERT INTO `quest_greeting` VALUES (234, 0, 'A foul corruption has crept into Westfall.  While I was upholding my duty on the battlefields of Lordaeron these honest farms were overrun and made into hide-outs for thugs and murderers. The People\'s Militia needs your help.', NULL, NULL, 'In Westfall hat sich üble Verderbnis eingeschlichen. Während ich auf dem Schlachtfeld von Lordaeron meine Pflicht tat, wurden diese anstandig geführten Höfe überfallen und zu Schlupfwinkeln für Schläger und Mörder umfunktioniert. Die Volksmiliz ist auf Eure Hilfe angewiesen.', NULL, NULL, 'Una corrupción asquerosa se ha infiltrado en Caída del Oeste. Mientras cumplía con mi deber en los campos de batalla de Lordaeron, estas honestas granjas fueron invadidas y convertidas en escondites de matones y asesinos. La Milicia Popular necesita tu ayuda.', NULL, 'Скверна проникла в Западный Край. Пока я сражался в боях за Лордерон, эти прекрасные фермы превратились в заброшенные руины, и в них поселились головорезы и убийцы. Народному ополчению нужна твоя помощь.', 1, 0);
INSERT INTO `quest_greeting` VALUES (6171, 0, 'You will be tested many times by the darkness that surrounds our lands, $N. But to ensure you are always prepared, we will often ask tasks of you so you are at the height of your own power.$B$BGo with the Light, and remain virtuous.', NULL, NULL, NULL, NULL, NULL, 'Serás probado muchas veces por la oscuridad que rodea nuestras tierras, $N. Pero para asegurarnos de que esté siempre preparado, a menudo le pediremos tareas para que esté a la altura de su propio poder. $B$BVaya con la Luz y siga siendo virtuoso.', NULL, 'Ты не однократно будешь проходить испытания во тьме, окружающей наши земли, $n. Но чтобы ты всегда $gбыл:была; наготове и сила твоя не ослабла, мы будем часто поручать тебе задания.$B$BСтупай со Светом и оставайся $gдобродетельным:добродетельной;.', 1, 0);
INSERT INTO `quest_greeting` VALUES (714, 0, 'Greetings, $c! Fine day for hunting, wouldn\'t you say? I\'ve been having more than a little luck with boars, myself. Perhaps you\'d like a shot?', NULL, NULL, NULL, NULL, NULL, '¡Saludos, $c! Buen día para cazar, ¿no crees? Yo también he tenido más que un poco de suerte con los jabalíes. ¿Quizás te gustaría un trago?', NULL, 'Приветствую, $c! Прекрасный день для охоты, не правда ли? У меня не большие проблемы с кабанами. Не желаешь поохотиться?', 0, 0);
INSERT INTO `quest_greeting` VALUES (2930, 0, 'Corruption sneaks into nature\'s grove. The forest must be protected at all costs.', NULL, NULL, NULL, NULL, NULL, 'La corrupción se cuela en la arboleda de la naturaleza. El bosque debe protegerse a toda costa.', NULL, 'Порча пробирается в рощу природы. Лес должен быть защищен любой ценой.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3649, 0, 'Dark forces encroach upon our borders, ancient taints resurface, and new evils emerge to topple the delicate balance of the land. In times of such darkness, we all must be vigilant.', NULL, NULL, NULL, NULL, NULL, 'Las fuerzas oscuras invaden nuestras fronteras, resurgen antiguas corrupciones y surgen nuevos males para derribar el delicado equilibrio de la tierra. En tiempos de tanta oscuridad, todos debemos estar atentos.', NULL, 'Темные силы посягают на наши границы, возрождается древняя зараза, появляется новое зло желающее разрушить тонкий баланс земли. В эти темные времена мы все должны быть бдительны.', 1, 0);
INSERT INTO `quest_greeting` VALUES (3616, 0, 'The wind whispers to those who listen...$B$BDo you hear it?', NULL, NULL, NULL, NULL, NULL, 'El viento susurra a los que escuchan ... $B$B¿Lo escuchas?', NULL, 'Ветер шепчет тем, кто слушает...$B$BТы слышишь его?', 0, 0);
INSERT INTO `quest_greeting` VALUES (3845, 0, 'We elves have a long history.  Let us hope this history does not return to haunt us.', NULL, NULL, NULL, NULL, NULL, 'Los elfos tenemos una larga historia. Esperemos que esta historia no vuelva a atormentarnos.', NULL, 'У нас эльфов большая история. Будем надеяться, что она никогда не повторится, и не будет преследовать нас.', 0, 0);
INSERT INTO `quest_greeting` VALUES (4077, 0, 'If I can get the proper ingredients, we can create some explosives that will not only allow me to damage the Venture\'s Co.\'s operations, but also cause a distraction.$B$BI know you\'re impressed, but it gets better... I\'ll tell you more soon enough.', NULL, NULL, NULL, NULL, NULL, 'Si puedo conseguir los ingredientes adecuados, podemos crear algunos explosivos que no solo me permitirán dañar las operaciones de Venture\'s Co., sino que también causarán una distracción. $B$BSé que estás impresionado, pero se pone mejor. .. Te contaré ahora.', NULL, 'Если я заполучу все необходимые ингредиенты, я смогу создать взрывчатку, которая не только нанесет урон Торговой Компании, но еще и отвлечет ее.$B$BЯ знаю что тебя это впечатлило, но еще лучше... обо всем остальном я расскажу тебе позже.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3419, 0, 'For our people to survive, we must study the ways of nature and learn its secrets.', NULL, NULL, NULL, NULL, NULL, 'Para que nuestra gente sobreviva, debemos estudiar los caminos de la naturaleza y aprender sus secretos.', NULL, 'Чтобы выжили наши люди, мы должны изучить пути природы и познать ее секреты.', 1, 0);
INSERT INTO `quest_greeting` VALUES (238, 0, 'Sometimes I think there\'s a big gray cloud in the sky, just raining down bad luck upon us. First, we\'re driven off our land, and now we can\'t even get out of Westfall. Everything\'s a mess. Something needs to be done.', NULL, NULL, 'Manchmal denke ich, eine große dunkle Wolke schwebt über uns, aus der Unglück auf uns herabregnet. Erst werden wir von unserem Land vertrieben und jetzt kommen wir noch nicht einmal aus Westfall weg. Alles liegt im Argen. Es muss etwas geschehen.', NULL, NULL, 'A veces pienso que hay una gran nube gris en el cielo, simplemente lloviendo mala suerte sobre nosotros. Primero, somos expulsados de nuestra tierra y ahora ni siquiera podemos salir de Caída del Oeste. Todo es un desastre. Algo se tiene que hacer.', NULL, 'Иногда мне кажется, что в небе есть огромное серое облако, которое льет на нас дождем невезенья. Сперва у нас отобрали нашу землю, а теперь мы даже не можем выбраться из Западного Края. Все это неправильно и с этим нужно что-то делать.', 0, 0);
INSERT INTO `quest_greeting` VALUES (235, 0, 'Welcome to our humble abode! It\'s always nice to see a friendly face. And what strong arms you have. My husband and I are always looking for help around the farm. Now that most the good folk have left, it\'s hard to find an able body to help out.', NULL, NULL, 'Willkommen in unserer bescheidenen Hüttel Wir freuen uns über jedes freundliche Gesicht. Und ihr habt so starke Arme. Mein Mann und ich sind ständig auf der Suche nach jemandem, der uns auf dem Hof häft. Jetzt, wo die ganzen guten Leute weg sind, ist es nicht einfach, kräftige Helfer zu bekommen.', NULL, NULL, '¡Bienvenido a nuestra humilde morada! Siempre es bueno ver una cara amiga. Y qué brazos tan fuertes tienes. Mi esposo y yo siempre buscamos ayuda en la granja. Ahora que la mayoría de la gente buena se ha ido, es difícil encontrar un cuerpo capaz de ayudar.', NULL, 'Добро пожаловать в наш скромный обитель! Всегда приятно видеть дружелюбное лицо. Какое у тебя крепкое оружие, а нам с мужем всегда нужна помощь в округе нашей фермы, ведь теперь, когда большинство людей ушло, сложно найти кого-то, кто способен помочь.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1518, 0, 'The Dark Lady has put forth the challenge. It is up to us to meet it.', NULL, NULL, 'Die dunkle Fürstin hat die Herausforderung gestellt. Es liegt an uns, sie anzunehmen.', NULL, NULL, 'La Dama Oscura ha presentado el desafío. Depende de nosotros afrontarlo.', NULL, 'Темная Госпожа поставила нам задачу, и мы должны решить ее.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1500, 0, 'I hope you\'re well, all things considered.\r\n\r\nSit for a spell, and hear my tale. It\'s a tragedy, of course, but one I hope will end in revenge!', NULL, NULL, 'Ich hoffe, Ihr seid den Umständen entsprechend wohlauf.\r\n\r\nNehmt doch hier Platz und lauscht meiner Geschichte. Natürlich ist es eine Tragödie, aber hoffentlich eine, die am Ende gerächt wird!', NULL, NULL, 'Siéntate un rato y escucha mi historia. Es una tragedia, por supuesto, ¡pero espero que termine en venganza!', NULL, 'Учитывая все обстоятельства, надеюсь, ты хорошо себя чувствуешь.$B$BПрисаживайся и выслушай мой рассказ, трагедию, которая я надеюсь закончиться местью!', 0, 0);
INSERT INTO `quest_greeting` VALUES (1515, 0, 'The Scarlet Crusade is encroaching on our homeland. The foolish zealots do not realize that the loyal servants of The Dark Lady shall see to their demise.', NULL, NULL, 'Der Scharlachrote Kreuzzug rückt unserer Heimat näher. Die törichten Eiferer erkennen nicht, dass die treuen Diener der dunklen Fürstin alles tun werden, um sie zu töten.', NULL, NULL, 'La Cruzada Escarlata está invadiendo nuestra patria. Los tontos fanáticos no se dan cuenta de que los leales sirvientes de La Dama Oscura se encargarán de su desaparición.', NULL, 'Алый орден вторгся в наши земли. Эти глупые фанатики еще не понимают, что верные слуги Темной Госпожи увидят их кончину.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1499, 0, 'Ah, you there! I have tasks to give, and I need not waste time explaining their crucial nature. Listen close.', NULL, NULL, 'He, Ihr da! Ich hätte da ein paar Aufgaben zu vergeben und muss unbedingt kurz erklären, wie außerordentlich wichtig sie sind. Hört gut zu.', NULL, NULL, '¡Ah, estás ahí! Tengo tareas que dar y no necesito perder el tiempo explicando su naturaleza crucial. Escuche atentamente.', NULL, 'А вот и ты! У меня есть для тебя несколько задач, но нет времени на их разъяснение. Так что слушай внимательно.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1495, 0, 'Greetings, $C. Be wary as you travel east toward The Bulwark. Recent surveillance reports indicate increased Scourge activity in that area, so exercise caution.', NULL, NULL, 'Seid gegrüßt, $C. Seid wachsam, wenn Ihr nach Osten zum Bollwerk reist. Aktuellen Spähermeldungen zufolge ist in dem Bereich eine erhöhte Aktivität der Greißel zu verzeichnen. Hier ist also Vorsicht geboten.', NULL, NULL, 'Saludos, $C. Tenga cuidado mientras viaja hacia el este hacia El Baluarte. Los informes de vigilancia recientes indican un aumento de la actividad de la Plaga en esa área, así que tenga cuidado.', NULL, 'Приветствую тебя, $c. Если ты направишься в Бастион, то будь $gосторожен:осторожна;. Недавние отчеты разведки указывают на увеличение активности Плети в этом районе.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3188, 0, 'There is something you wish to discuss, $c... come, sit by me.', NULL, NULL, NULL, NULL, NULL, 'Hay algo que desea discutir, $c ... ven, siéntate a mi lado.', NULL, 'Есть кое-что, что нужно обсудить, $c... проходи, присаживайся.', 0, 0);
INSERT INTO `quest_greeting` VALUES (5887, 0, 'I welcome you back, $n.', NULL, NULL, NULL, NULL, NULL, 'Te doy la bienvenida, $n.', NULL, 'Приветствую тебя, $n.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3139, 0, 'Throm\'ka, $c. There is little time for talk and much work to be done.', NULL, NULL, NULL, NULL, NULL, 'Throm\'ka, $c. Hay poco tiempo para hablar y mucho trabajo por hacer.', NULL, 'Тром\'ка, $c! Так мало времени для разговоров и так много работы предстоит сделать.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2519, 0, 'Hello! The spirits say you here to aid my chief. Say it loud, they do.', NULL, NULL, NULL, NULL, NULL, '¡Hola! Los espíritus dicen que estás aquí para ayudar a mi jefe. Dilo en voz alta, lo hacen.', NULL, 'Привет! Духи говорят что ты $gпришел:пришла; чтобы оказать помощь.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3338, 0, 'The land, the water and the sky are all as one. It is your eyes that deceive you with such separation. The Earthmother is all those things and more.', NULL, NULL, NULL, NULL, NULL, 'La tierra, el agua y el cielo son uno. Son tus ojos los que te engañan con tal separación. La Madre Tierra es todas esas cosas y más.', NULL, 'Земля, вода и небо едины. Разделение существует только в твоих глазах. Мать-Земля заключает в себя все, и даже более этого.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1343, 0, 'Well, if it isn\'t a young, bristling $c, no doubt drawn here by talk of my exploits in fields of battle!$B$BNo time for stories now, for there are great, important deeds that need doing!  So if you\'re looking for glory, then luck shines on you today...', NULL, NULL, NULL, NULL, NULL, 'Bueno, si no es un $c joven y erizado, ¡sin duda atraído aquí por hablar de mis hazañas en los campos de batalla! $B$B¡No hay tiempo para historias ahora, porque hay grandes e importantes hechos que deben hacerse! Entonces, si estás buscando la gloria, entonces la suerte brilla sobre ti hoy ...', NULL, 'Ну, кто это, как не $c, что рвется на поле брани со всем юным пылом? Несомненно, тебя привлекли сюда слухи о моих подвигах.$B$BСейчас не время для замшелых историй, но время для великих и доблестных свершений! Если ты ищешь славы, то сегодня удача улыбнулась тебе.', 1, 0);
INSERT INTO `quest_greeting` VALUES (3446, 0, 'Yes yes yes! You\'re just the $r I\'m looking for!\r\n\r\nSit! We have much to discuss!!', NULL, NULL, NULL, NULL, NULL, '¡Si si si! ¡Eres el $r que estoy buscando!\r\n\r\n¡Sientate! ¡¡Tenemos mucho que discutir!!', NULL, 'Да, да, да! Именно тебя мне и нужно, $r!$B$BПрисаживайся! Нам нужно многое обсудить!', 0, 0);
INSERT INTO `quest_greeting` VALUES (3453, 0, 'Something I can help you with, $n? There\'s a shipment I\'ve got to see to otherwise.', NULL, NULL, NULL, NULL, NULL, '¿Puedo ayudarte en algo, $n? Hay un envío que tengo que ocuparme si no te importa.', NULL, 'Я чем-то могу помочь тебе, $n? А то меня ждет партия товара.', 0, 0);
INSERT INTO `quest_greeting` VALUES (253, 0, 'Aha! Good day, good day, Master $C! Come, sit down and have a drink. You have an enterprising look in your eye, and I think you\'ll find speaking to me worth your time...', NULL, NULL, 'Aha! Guten Tag, guten Tag, Meister $C! Kommt, setzt Euch und trinkt etwas. Ihr habt so ein Leuchten in den Augen, als wolltet ihr gern etwas tun. Ich denke, Ihr solltet ein paar Wörtchen mit mir wechseln, es lohnt sich bestimmt...', NULL, NULL, '¡Ajá! ¡Buen día, buen día, Maestro $C! Ven, siéntate y tómate una copa. Tienes una mirada emprendedora, y creo que encontrarás que hablar conmigo vale la pena ...', NULL, 'Ага! Добрый день, добрый день, мастер $c! Пойдем, присядем и выпьем. У тебя предприимчивый взгляд, и я думаю, что ты не зря потратишь время на разговор со мной...', 0, 0);
INSERT INTO `quest_greeting` VALUES (737, 0, 'Well, hello there. You seem like you wouldn\'t be opposed to making some coin, hm? I can tell from the look in your eyes. I am Mogul Kebok, overseer of operations in Azeroth, and if it is riches you seek, perhaps I can make arrangements.', NULL, NULL, NULL, NULL, NULL, 'Bueno, hola. Parece que no se opondría a hacer una moneda, ¿eh? Puedo decirlo por la mirada en tus ojos. Soy Mogul Kebok, supervisor de operaciones en Azeroth, y si lo que busca son riquezas, tal vez pueda hacer los arreglos necesarios.', NULL, 'Ну, привет. Судя по твоим глазам, ты не откажешься от лишних звенящих монет, а? Я Могул Кебок, контролирую все операции в Азероте, и если ты ищешь богатства, возможно, мы сможем договориться.', 0, 0);
INSERT INTO `quest_greeting` VALUES (773, 0, '$C, eh? I am Krazek, Baron Revilgaz\'s secretary. I know everything about the goings on in this jungle and beyond. Perhaps you\'d be interested in knowing the going price on oil in Ratchet? No? Looking for work, maybe? I can help you there.', NULL, NULL, NULL, NULL, NULL, '$C, ¿eh? Soy Krazek, la secretaria del barón Revilgaz. Sé todo sobre lo que sucede en esta jungla y más allá. ¿Quizás le interesaría conocer el precio actual del petróleo en Ratchet? ¿No? ¿Buscas trabajo, tal vez? Te puedo ayudar allí.', NULL, '$c, а? Я Кразек, секретарь барона Ревилгаза. Я знаю все, что происходит в этих джунглях и за их пределами. Возможно, тебе будет интересно узнать цену на нефть в Кабестане? Нет? Может быть, ты ищешь работу? Я могу помочь тебе здесь.', 0, 0);
INSERT INTO `quest_greeting` VALUES (786, 0, 'Greetings, $G lad : lass;. I\'m Grelin Whitebeard. I\'m here to examine the threat posed by the growing numbers of trolls in Coldridge Valley. What have I found? It\'s a bit troubling...', NULL, NULL, NULL, NULL, NULL, 'Saludos, $G muchacho : muchacha ;. Soy Grelin Barbablanca. Estoy aquí para examinar la amenaza que representa el creciente número de trolls en Valle Cresta Fría. ¿Qué he encontrado? Es un poco preocupante ...', NULL, 'Привет. Я Грелин Белобород. Здесь я изучаю угрозу, исходящую от растущего числа троллей в Холодной долине. Что я нашел? Это и беспокоит...', 0, 0);
INSERT INTO `quest_greeting` VALUES (1374, 0, 'Curse that Brewers\' League! They have access to all the best ingredients, while we\'re stuck here grubbing for grain and hops!', NULL, NULL, NULL, NULL, NULL, '¡Maldita la Liga de los Cerveceros! Tienen acceso a los mejores ingredientes, ¡mientras nosotros estamos atrapados aquí buscando cereales y lúpulo!', NULL, 'Проклятая лига пивоваров! У них есть все лучшие ингредиенты, в то время как мы застряли здесь с зерном и шишками хмеля!', 0, 0);
INSERT INTO `quest_greeting` VALUES (1937, 0, 'The Dark Lady has put the challenge forth.  Now it is up to the Royal Apothecary Society to develop a new plague.  We shall bring Arthas and his wretched army to their knees.', NULL, NULL, NULL, NULL, NULL, 'La Dama Oscura ha presentado el desafío. Ahora le toca a la Sociedad Real de Boticarios desarrollar una nueva plaga. Haremos que Arthas y su miserable ejército se pongan de rodillas.', NULL, 'Темная Госпожа поручила Королевскому фармацевтическому обществу разработать новую чуму. Мы поставим Артаса и его мерзкую армию на колени.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2076, 1, 'This cauldron churns with thick, green bubbles.  Skulls, bones and organs of unknown creatures swim within its viscous broth...$B$BAnd rising lazily to the surface are the skulls of two, once mighty trolls:$B$BGan\'zulah and Nezzliok.', NULL, NULL, NULL, NULL, NULL, 'Este caldero se agita con gruesas burbujas verdes. Cráneos, huesos y órganos de criaturas desconocidas nadan dentro de su caldo viscoso ... $B$BY subiendo perezosamente a la superficie están los cráneos de dos, una vez poderosos trolls: $B$BGan\'zulah y Nezzliok.', NULL, 'Котел бурлит большими зелеными пузырями. Черепа, кости, органы неизвестных существ плавают внутри этого вязкого бульона...$B$BНа поверхность лениво всплывают черепа двух некогда могучих троллей, Ган\'зулаха и Неззилока.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2121, 0, 'Information... With our scouts and agents, we control the flow of information in Lordaeron. Scourge movements, their holdings, all underneath our watchful eyes...', NULL, NULL, NULL, NULL, NULL, 'Información ... Con nuestros exploradores y agentes, controlamos el flujo de información en Lordaeron. Los movimientos de la plaga, sus posesiones, todo bajo nuestra atenta mirada ...', NULL, 'Информация... Благодаря нашим разведчикам и агентам мы контролируем поток информации в Лордероне. Передвижение Плети, их запасы, все под нашим бдительным оком...', 0, 0);
INSERT INTO `quest_greeting` VALUES (2285, 0, 'My family boasts the finest collection of jewelry and objects of fine art among all the nobles of Stormwind!$B$BAnd we are always wishing to increase the size our collection...', NULL, NULL, NULL, NULL, NULL, '¡Mi familia cuenta con la mejor colección de joyas y objetos de bellas artes entre todos los nobles de Ventormenta! $B$BY siempre estamos deseando aumentar el tamaño de nuestra colección ...', NULL, 'Моя семья может похвастаться лучшей коллекцией ювелирных изделий и предметами искусства среди всех дворян Штормграда!$B$BИ мы всегда жаждем расширить свою коллекцию...', 0, 0);
INSERT INTO `quest_greeting` VALUES (2498, 0, 'What what?!?  We all have profit to make... and we won\'t do it by standing idle.', NULL, NULL, NULL, NULL, NULL, '¿¡¿Que que?!? Todos tenemos beneficios que hacer ... y no lo haremos si permanece inactivo.', NULL, 'Что-что?! Мы все получаем прибыль, занимаясь... и останься мы без дела, у нас ничего этого не будет.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2921, 0, 'How perfect of you to come by, $c.$B$BMy name is Lotwil Veriatus, founding member of the Enlightened Assembly of Arcanology, Alchemy, and Engineering Sciences: we seek to blend the intelligent sciences of Azeroth together into one comprehensive school.', NULL, NULL, NULL, NULL, NULL, 'Qué perfecto por tu parte, $c. $B$BMi nombre es Lotwil Veriatus, miembro fundador de la Asamblea Iluminada de Arcanología, Alquimia y Ciencias de la Ingeniería: buscamos combinar las ciencias inteligentes de Azeroth en una sola escuela integral.', NULL, 'Как хорошо, что ты здесь, $c.$B$BМеня зовут Лотвиль Вериатус и я состою в Просвещенной Ассамблее Чародейства, Алхимии и Технических Наук. Мы стремимся объединить интеллектуальные науки Азерота в одну общеобразовательную школу.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3391, 0, 'Thrall paid me and my boys well for helping out with the construction of Orgrimmar, so I decided to set up a port here. We do most of our business through Booty Bay and Baron Revilgaz.', NULL, NULL, NULL, NULL, NULL, 'Thrall me pagó bien a mí y a mis muchachos por ayudar en la construcción de Orgrimmar, así que decidí establecer un puerto aquí. Hacemos la mayor parte de nuestro negocio a través de La Bahía Botín y Baron Revilgaz.', NULL, 'Тралл заплатил мне и моим ребятам за помощь в строительстве Оргриммара, так что я решил основать здесь порт. В основном мы обделываем делишки в Пиратской Бухте, через барона Ревилгаза.', 0, 0);
INSERT INTO `quest_greeting` VALUES (4791, 0, 'We may not be in open war with the Alliance, but blood is still shed between us.', NULL, NULL, NULL, NULL, NULL, 'Puede que no estemos en guerra abierta con la Alianza, pero aún se derrama sangre entre nosotros.', NULL, 'Может мы и не в открытой войне с Альянсом, но между нами все еще льется кровь.', 1, 0);
INSERT INTO `quest_greeting` VALUES (5204, 0, 'If we are to make our place in this world, then we will do so through study, and through the will to ignore our fading human instincts.', NULL, NULL, NULL, NULL, NULL, 'Si queremos hacer nuestro lugar en este mundo, lo haremos mediante el estudio y la voluntad de ignorar nuestros instintos humanos que se desvanecen.', NULL, 'Если мы хотим занять свое место в этом мире, мы должны заниматься исследованиями, а также игнорировать наши угасающие человеческие инстинкты.', 0, 0);
INSERT INTO `quest_greeting` VALUES (5394, 0, 'Don\'t let the heat bother you.  In the Badlands, heat is the least of your worries.', NULL, NULL, NULL, NULL, NULL, 'No dejes que el calor te moleste. En las Tierras Malas, el calor es la menor de tus preocupaciones.', NULL, 'Не позволяй жаре беспокоить себя. В Бесплодных землях она наименьшая из проблем.', 1, 0);
INSERT INTO `quest_greeting` VALUES (5591, 0, 'This sty\'s a little shy of comfy, but it has history, so Stonard must be important to someone. I\'d gamble that\'s why we stay here. It sure ain\'t for the view--it don\'t even look like home.', NULL, NULL, NULL, NULL, NULL, 'Este jardín es un poco tímido para ser cómodo, pero tiene historia, por lo que Stonard debe ser importante para alguien. Apostaría a que es por eso que nos quedamos aquí. Seguro que no es para la vista, ni siquiera se ve como en casa.', NULL, 'Этот свинарник не очень-то удобен, но у него есть своя история, и для кого-то Каменор, наверное, важен. Мне еще повезло, что мы тут застряли. Конечно, не из-за его красот, - это место трудно назвать даже подобием дома.', 1, 0);
INSERT INTO `quest_greeting` VALUES (7407, 0, 'The name\'s Bilgewhizzle, and I am the chief engineer of the Gadgetzan Water Company.  What can I assist you with?', NULL, NULL, NULL, NULL, NULL, 'Me llamo Silbido Sentimental y soy el ingeniero jefe de la Compañía de Agua de Artilugiozan. ¿En qué te puedo ayudar?', NULL, 'Меня зовут Чепухастер и я главный инженер компании \"Воды Прибамбасска\". Чем я могу помочь тебе?', 0, 0);
INSERT INTO `quest_greeting` VALUES (7876, 0, 'Some people wonder what we\'re doing out here in the desert.  Well... if I told you, then you\'d stay and try to make our profits!', NULL, NULL, NULL, NULL, NULL, 'Algunas personas se preguntan qué estamos haciendo aquí en el desierto. Bueno ... si te lo dijera, ¡entonces te quedarías y tratarías de obtener nuestras ganancias!', NULL, 'Некоторые задаются вопросом, чем мы занимаемся здесь, в пустыне. Что ж... если я расскажу тебе, тогда ты останешься здесь и попытаешься получить от этого нашу прибыль!', 1, 0);
INSERT INTO `quest_greeting` VALUES (7882, 0, 'We\'re here to make a profit.  And having our goods stolen is no way to make a profit.', NULL, NULL, NULL, NULL, NULL, 'Estamos aquí para obtener ganancias. Y que nos roben nuestros bienes no es una forma de obtener ganancias.', NULL, 'Мы здесь ради прибыли, а украденные товары этому не способствуют.', 1, 0);
INSERT INTO `quest_greeting` VALUES (7900, 0, 'Hello, $N. Perhaps you have some time to chat?', NULL, NULL, NULL, NULL, NULL, 'Hola, $N. ¿Quizás tienes algo de tiempo para charlar?', NULL, 'Привет, $n. У тебя не найдется времени поговорить?', 0, 0);
INSERT INTO `quest_greeting` VALUES (9078, 0, 'Dear $g boy:girl;, you have arrived just in time to assist the Kargath Expeditionary Force.', NULL, NULL, NULL, NULL, NULL, 'Estimado $g chico: chica; llegaste justo a tiempo para ayudar a la Fuerza Expedicionaria de Kargath.', NULL, '$gДорогой друг:Дорогая подруга;, вы прибыли как раз вовремя, чтобы оказать помощь экспедиционному корпусу Каргата.', 1, 0);
INSERT INTO `quest_greeting` VALUES (10926, 0, 'I never feel warm anymore...', NULL, NULL, NULL, NULL, NULL, 'Nunca me siento cálido ...', NULL, 'Я больше никогда не почувствую тепла...', 0, 0);
INSERT INTO `quest_greeting` VALUES (11039, 0, 'Greetings, $N. I am Duke Nicholas Zverenhoff of the Argent Dawn.', NULL, NULL, NULL, NULL, NULL, 'Saludos, $N. Soy el duque Nicholas Zverenhoff del Alba Argenta.', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (342, 0, 'Hail, $n. Welcome to my humble garden. The weather has been perfect lately. Let us hope it holds steady for a ripe harvest.', NULL, NULL, NULL, NULL, NULL, 'Salve, $n. Bienvenidos a mi humilde jardín. El clima ha sido perfecto últimamente. Esperemos que se mantenga firme para una cosecha madura.', NULL, 'Приветствую, $n! Добро пожаловать в мой скромный сад. В эти дни погода прекрасна. Будем надеяться, что она останется такой же до созревания урожая.', 0, 0);
INSERT INTO `quest_greeting` VALUES (240, 0, 'Ach, it\'s hard enough keeping order around here without all these new troubles popping up!  I hope you have good news, $n...', '어이쿠, 이렇게 자꾸 새로운 문제가 발생해서는 이곳 주위의 질서를 바로잡기가 어렵습니다! $n, 당신이 좋은 소식을 가져왔으면 좋겠군요...', 'Ha, c\'est déjà pas facile de maintenir l\'ordre par ici sans rajouter tous ces nouveaux problèmes ! J\'espère que vous apportez de bonnes nouvelles, $n...', 'Ach, es ist schon schwierig, hier Ordnung zu wahren, auch ohne die ganzen neu aufgetretenen Probleme! Ihr habt hoffentlich gute Neuigkeiten, $n...', '啊，就算没有这些新麻烦不断的冒出来，维持这儿的秩序就已经够让人头痛的了！希望你有好消息，$n……', '唉，光要管好這邊的秩序已經很不容易了，更何況還有這麼多的新問題一直冒出來。我希望你帶來的是好消息，$n...', '¡Ay, ya es difícil mantener el orden por aquí sin que aparezcan de repente todos esos nuevos problemas! ¡Espero que traigas buenas noticias, $n...', '¡Ay, ya es difícil mantener el orden por aquí sin que aparezcan de repente todos esos nuevos problemas! ¡Espero que traigas buenas noticias, $n...', 'Ох, и без этих новых проблем было довольно сложно поддерживать здесь порядок! Надеюсь, у тебя хорошие новости, $n...', 0, 0);
INSERT INTO `quest_greeting` VALUES (2215, 0, 'In order to serve the Dark Lady and Varimathras we need to advance the front on the Human Infestation.', NULL, NULL, NULL, NULL, NULL, 'Para poder servir a la Dama Oscura y Varimathras necesitamos avanzar en el frente de la Infestación Humana.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (2216, 0, 'We are but so close to developing the New Plague that our Dark Lady desires with such fervor.', NULL, NULL, NULL, NULL, NULL, 'Estamos tan cerca de desarrollar la Nueva Plaga que nuestra Dama Oscura desea con tanto fervor.', NULL, 'Мы так близки к созданию Новой Чумы, которую с таким нетерпением ждет наша Темная Госпожа.', 0, 0);
INSERT INTO `quest_greeting` VALUES (264, 0, 'At ease, $c. If you are just passing though I suggest you stick to the roads and only travel by day. If your business is here in Darkshire, consider lending your abilities to the Night Watch. Our Skill is unquestionable but our numbers are small.', NULL, NULL, NULL, NULL, NULL, 'Tranquilo, $c. Si solo está pasando, le sugiero que no se separe de las carreteras y viaje solo de día. Si su negocio está aquí en Comarca Oscura, considere prestar sus habilidades a la Guardia Nocturna. Nuestra habilidad es incuestionable pero nuestro número es pequeño.', NULL, 'Если ты просто прогуливаешься, $c, то лучше держаться дороги и делать это только днем. Если дела ждут тебя здесь в Темнолесье, то стоит заглянуть к Ночному Дозору. Наши навыки неоспоримы, но ряды наши малы.', 0, 0);
INSERT INTO `quest_greeting` VALUES (344, 0, 'Redridge is awash in chaos!', NULL, NULL, NULL, NULL, NULL, '¡Cresta Roja está inundado de caos!', NULL, 'Красногорье погружено в хаос!', 5, 0);
INSERT INTO `quest_greeting` VALUES (392, 0, 'Do not be alarmed, $r.  I have long since passed from this land but I intend no harm to your kind.  I have witnessed too much death in my time.  My only wish now is for peace.  Perhaps you can help my cause.', NULL, NULL, NULL, NULL, NULL, 'No te alarmes, $r. Hace mucho que dejé esta tierra, pero no pretendo hacer daño a los de tu especie. He sido testigo de demasiadas muertes en mi época. Mi único deseo ahora es la paz. Quizás puedas ayudar a mi causa.', NULL, 'Не бойся, $r. Меня уже давно нет в этом мире, и я не желаю тебе зла. В свое время мне пришлось повидать слишком много смертей и моим единственным желанием сейчас является достижение мира. Возможно, ты сможешь помочь моему делу.', 0, 0);
INSERT INTO `quest_greeting` VALUES (900, 0, 'What business brings you before the Court of Lakeshire and the Honorable Magistrate Solomon?', NULL, NULL, NULL, NULL, NULL, '¿Qué asunto le trae ante el Tribunal de Lago Condado y el honorable magistrado Solomon?', NULL, 'Какие дела привели тебя к ратуше Приозерья и уважаемому мировому судье Соломону?', 6, 0);
INSERT INTO `quest_greeting` VALUES (2080, 0, 'The creation of Teldrassil was a grand achievement, but now the world must shift to regain its balance.', NULL, NULL, NULL, NULL, NULL, 'La creación de Teldrassil fue un gran logro, pero ahora el mundo debe cambiar para recuperar el equilibrio.', NULL, 'Создание Тельдрассила было огромным достижением, но теперь, чтобы восстановить равновесия, мир должен измениться.', 1, 0);
INSERT INTO `quest_greeting` VALUES (3337, 0, 'The heft of an axe, the battlecry of your allies, the spray of blood in your face. These are the things a warrior craves, $n. I will carve out The Barrens with my sword in the name of the Horde.', NULL, NULL, NULL, NULL, NULL, 'El peso de un hacha, el grito de batalla de tus aliados, el chorro de sangre en tu rostro. Estas son las cosas que anhela un guerrero, $n. Tallaré Los Baldíos con mi espada en nombre de la Horda.', NULL, 'Лезвие топора оставит брызги крови врага на твоем лице. Это то, чего жаждет каждый воин, $n. Я очищу Степи, своим мечем, во имя Орды.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3339, 0, 'This had better be good...', NULL, NULL, NULL, NULL, NULL, 'Será mejor que sea buena ...', NULL, 'Это было бы лучше...', 0, 0);
INSERT INTO `quest_greeting` VALUES (3390, 0, 'The Barrens holds a variety of substances for which we, the apothecaries of Lordaeron may find use.', NULL, NULL, NULL, NULL, NULL, 'Los Baldíos contienen una variedad de sustancias para las que nosotros, los boticarios de Lordaeron, podemos encontrar uso.', NULL, 'В Степях находятся различные материалы, которым мы – аптекари Лордерона можем найти применение.', 1, 1);
INSERT INTO `quest_greeting` VALUES (3519, 0, 'I, Arynia Cloudsbreak, have been tasked with protecting the sanctity of the Oracle Grove.', NULL, NULL, NULL, NULL, NULL, 'A mí, Arynia Rompenubes, se me ha encomendado la tarea de proteger la santidad del Arboleda Oráculo.', NULL, 'Я Арания Проблеск Солнца, моя задача охранять Поляну Оракула.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3567, 0, 'Well met, $n. It is good to see that $cs like yourself are taking an active part in protecting the groves.', NULL, NULL, NULL, NULL, NULL, 'Bien conocido, $n. Es bueno ver que $cs como usted están participando activamente en la protección de las arboledas.', NULL, 'Приятно встретить вас, $n. Хорошо, что такой $c как вы, принимает активное участие в защите рощ.', 1, 0);
INSERT INTO `quest_greeting` VALUES (3847, 0, 'Ashenvale is a lush forest, brimming with life. It is a pleasure to walk down its secret paths in search of herbs, but one must take care. The forest is not without its dangers.', NULL, NULL, NULL, NULL, NULL, 'Vallefresno es un bosque frondoso, rebosante de vida. Es un placer recorrer sus senderos secretos en busca de hierbas, pero hay que tener cuidado. El bosque no está exento de peligros.', NULL, 'Ясеневый лес – пышный, наполненный жизнью лес. Очень приятно ходить по тайным тропам в поиске трав. Но этот лес не лишен опасностей.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3995, 0, 'The spirits are restless!', NULL, NULL, NULL, NULL, NULL, '¡Los espíritus están inquietos!', NULL, 'Духи обеспокоены!', 5, 0);
INSERT INTO `quest_greeting` VALUES (4049, 0, 'The spirit of Stonetalon weeps... It weeps from its mountain peaks, to its rivers, to its severed, dying trees.', NULL, NULL, NULL, NULL, NULL, 'El espíritu de Espolón llora ... Llora desde los picos de sus montañas, a sus ríos, a sus árboles cortados y moribundos.', NULL, 'Дух Когтистых гор плачет... Он плачет от своих горных вершин до рек, срезанных и мертвых деревьев.', 0, 0);
INSERT INTO `quest_greeting` VALUES (5767, 0, 'Our only hope is to create something good from an already bad situation.', NULL, NULL, NULL, NULL, NULL, 'Nuestra única esperanza es crear algo bueno a partir de una situación que ya es mala.', NULL, 'Нашей единственной надеждой является появление чего-то хорошего в ужасной ситуации.', 1, 0);
INSERT INTO `quest_greeting` VALUES (2706, 0, 'Thanks to the Warchief, even here in the ruins of our former prison some hope remains, and the Horde rises anew.', NULL, NULL, NULL, NULL, NULL, 'Gracias al Jefe de Guerra, incluso aquí, en las ruinas de nuestra antigua prisión, queda algo de esperanza y la Horda resurge de nuevo.', NULL, 'Благодаря Вождю, даже здесь, в руинах нашей некогда тюрьмы, остается надежда, что однажды Орда вновь возродится.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2817, 0, 'You must be hard up to be wandering this Badlands, $c. A hard up like me.$B$BOr maybe you\'re here because you\'re crazy. Crazy, like me.', NULL, NULL, NULL, NULL, NULL, 'Debes tener muchas ganas de deambular por estas Tierras Inhóspitas, $c. Un duro como yo. $B$BO tal vez estás aquí porque estás loco. Loco, como yo.', NULL, 'Должно быть, тебе сложно бродить по этим Бесплодным землям, $c. Сложно, как и мне.$B$BИли может, ты здесь лишь потому что $gтакой же сумасшедший:такая же сумасшедшая; как и я.', 0, 0);
INSERT INTO `quest_greeting` VALUES (4046, 0, 'You must listen, young $c.  Listen to the whisperings in the darkness, for they offer guidance in these troubled times.', NULL, NULL, NULL, NULL, NULL, 'Debes escuchar, joven $c. Escuche los susurros en la oscuridad, porque ofrecen guía en estos tiempos difíciles.', NULL, 'Тебе стоит прислушаться, юный $c. Прислушайся к шепотам во тьме, они дадут совет в эти темные времена.', 1, 0);
INSERT INTO `quest_greeting` VALUES (4452, 0, 'Come a little closer.  We have important matters to discuss, you and I.$B$BAnd some of them we don\'t want everyone to hear...', NULL, NULL, NULL, NULL, NULL, 'Acercate un poco mas. Tenemos asuntos importantes que discutir, tú y yo. $B$BY algunos de ellos no queremos que escuchen ...', NULL, 'Подойди поближе. Есть важные вопросы, которые нам следует обсудить.$B$BНо и есть то, чего не следует тебе слышать...', 0, 0);
INSERT INTO `quest_greeting` VALUES (4498, 0, 'Greetings, $c.', NULL, NULL, NULL, NULL, NULL, 'Buenas, $c.', NULL, 'Приветствую вас, $c.', 0, 0);
INSERT INTO `quest_greeting` VALUES (5412, 0, 'The centaur clans rule the wastes of Desolace. If united, they would be a terrible force. It is then good that the centaur clans are not united but instead bicker and war amongst themselves.', NULL, NULL, NULL, NULL, NULL, 'Los clanes de los centauros gobiernan los páramos de Desolace. Si se unen, serían una fuerza terrible. Entonces es bueno que los clanes de centauros no estén unidos, sino que peleen y luchen entre ellos.', NULL, 'Кланы кентавров управляют участками Пустошей. Если бы они объединились, то они бы стали ужасной силой. Очень хорошо, что кланы вместо объединения выбрали путь сражения друг с другом.', 0, 0);
INSERT INTO `quest_greeting` VALUES (5641, 0, 'The main threat Thrall wishes dealt with is the Burning Blade---members of the Horde that have given their loyalty to the demons. They seek to practice their dark magic and care little for Thrall\'s visions of the Horde\'s future here in Kalimdor.', NULL, NULL, NULL, NULL, NULL, 'La principal amenaza con la que Thrall desea lidiar es la Hoja Ardiente, miembros de la Horda que han dado su lealtad a los demonios. Buscan practicar su magia oscura y se preocupan poco por las visiones de Thrall sobre el futuro de la Horda aquí en Kalimdor.', NULL, 'Главная угроза, с которой Тралл хочет расправиться, это Пылающий Клинок – члены Орды, которые дали клятву своей верности демонам. Они стремятся к тому, чтобы улучшать свои навыки темной магии, и их мало заботят видения Тралла о будущем Орды здесь в Калимдоре.', 1, 0);
INSERT INTO `quest_greeting` VALUES (10537, 0, 'We cannot take care of all the threats in this area alone. We could use another fighting hand, $n.', NULL, NULL, NULL, NULL, NULL, 'No podemos hacernos cargo de todas las amenazas en esta área solos. Nos vendría bien otra mano de lucha, $n.', NULL, 'Мы не можем разобраться со всеми угрозами, находящимися в этой местности. И мы бы не отказались воспользоваться рукой помощи, $n.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1776, 0, 'We spent so much of our lives in fight, memories of peaceful times grow evermore distant.', NULL, NULL, NULL, NULL, NULL, 'Pasamos gran parte de nuestras vidas luchando, los recuerdos de tiempos pacíficos se vuelven cada vez más distantes.', NULL, 'Большую часть нашей жизни мы провели, сражаясь, а воспоминания о мирных временах уже стерлись из памяти.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1950, 0, 'My brother and I are on a scouting mission, but we are holed up in this farmhouse. The Deathstalkers need your help!', NULL, NULL, NULL, NULL, NULL, 'Mi hermano y yo estamos en una misión de exploración, pero estamos escondidos en esta granja. ¡Los Acechadores de la muerte necesitan tu ayuda!', NULL, 'Мы с братом выполняем разведывательную миссию, но застряли в этом доме. Ловчим смерти нужна ваша помощь!', 0, 0);
INSERT INTO `quest_greeting` VALUES (3441, 0, 'To hunt a beast, one must know that beast.  One must learn and respect its ways.$B$BTo do otherwise is not to hunt.  To do otherwise is merely to kill.', NULL, NULL, NULL, NULL, NULL, 'Para cazar una bestia, hay que conocerla. Hay que aprender y respetar sus caminos. $B$BHacer lo contrario no es cazar. Hacer lo contrario es simplemente matar.', NULL, 'Чтобы охотится на зверя, нужно знать этого зверя. Нужно изучать и уважать его пути.$B$BИначе это не охота, а просто убийство.', 0, 0);
INSERT INTO `quest_greeting` VALUES (4485, 0, 'The days grow long, and still no end to the conflicts of these lands can be seen. It takes no spell caster to know that much. Take up a blade while you can, $c. War can come to our doors at any time, and if I\'m not mistaken, you look to be one who revels in it.', NULL, NULL, NULL, NULL, NULL, 'Los días se alargan y aún no se vislumbra el final de los conflictos de estas tierras. No hace falta ningún lanzador de hechizos para saber tanto. Toma una cuchilla mientras puedas, $c. La guerra puede llegar a nuestras puertas en cualquier momento, y si no me equivoco, pareces ser alguien que se deleita con ella.', NULL, 'Дни длятся очень долго, а конфликтам на этих землях нет конца. Возьми свое оружие, $c. Война может придти в любое время, и если я не ошибаюсь, ты выглядишь как $gодин:одна; из тех, кто упивается ею.', 1, 0);
INSERT INTO `quest_greeting` VALUES (4500, 0, 'Overlord Mok\'Morokk boss. You do what I say.', NULL, NULL, NULL, NULL, NULL, 'Jefe del Señor Mok\'Morokk. Haz lo que te digo.', NULL, 'Властитель Мок\'Морокк здесь босс, и ты будешь делать то, что я скажу.', 0, 0);
INSERT INTO `quest_greeting` VALUES (6986, 0, 'My name is Dran Droffers, and this over here is my dummy son Malton.  If you need salvage, or are looking to sell salvage, then we\'re who you need to be talking to!', NULL, NULL, NULL, NULL, NULL, 'Mi nombre es Dran Droffers, y este de aquí es mi hijo tonto Malton. Si necesita salvamento, o está buscando vender salvamento, ¡entonces somos con quién debe hablar!', NULL, 'Меня зовут, Дран Дрофферс, а это мой глупый сын, Мальтон. Если вам нужна помощь или вы хотите продать некоторые из своих вещей, тогда мы именно те, кто вам нужен!', 1, 0);
INSERT INTO `quest_greeting` VALUES (9536, 0, 'The quest for wealth is the only goal for a respectable goblin.$B$BWell, maybe wealth... and a big, loud death!', NULL, NULL, NULL, NULL, NULL, 'La búsqueda de la riqueza es el único objetivo de un goblin respetable. $B$BBueno, tal vez la riqueza ... ¡y una gran y ruidosa muerte!', NULL, 'Поиск сокровища – единственная значимая цель для гоблина.$B$BНу, может, сокровища... и большая, громкая смерть!', 0, 0);
INSERT INTO `quest_greeting` VALUES (2497, 0, 'Eh?  You have business with Nimboya?', NULL, NULL, NULL, NULL, NULL, '¿Eh? ¿Tiene negocios con Nimboya?', NULL, 'А? Какие дела привели тебя к Нимбойе?', 0, 0);
INSERT INTO `quest_greeting` VALUES (715, 0, 'Another fine day in the jungle!  It\'s going to be quite a hunt,  I can feel it.  Once Barnil is done cleaning the guns, I\'m taking the hunting party deep into the twisting vines.  Not such a bad way for an old war vet to spend his retirement, eh?', NULL, NULL, NULL, NULL, NULL, '¡Otro buen día en la jungla! Va a ser una gran cacería, puedo sentirlo. Una vez que Barnil haya terminado de limpiar las armas, llevaré al grupo de caza a lo más profundo de las enredaderas retorcidas. No es una mala manera para que un veterano de guerra pase su jubilación, ¿eh?', NULL, 'Еще один прекрасный день в джунглях! Сегодня будет отличная охота, я чувствую это. Как только Барнил завершит с чисткой моего оружия, я отправлюсь на охоту. Не так уж и плохо для ветерана войны, а?', 0, 0);
INSERT INTO `quest_greeting` VALUES (2501, 0, 'Oy!  You here for a game of knuckles?', NULL, NULL, NULL, NULL, NULL, '¡Oy! ¿Estás aquí por un juego de nudillos?', NULL, 'Йоу! Хочешь сыграть?', 0, 0);
INSERT INTO `quest_greeting` VALUES (5598, 0, 'What do you ask of me?', NULL, NULL, NULL, NULL, NULL, '¿Qué me pides?', NULL, 'О чем ты хочешь спросить меня?', 6, 0);
INSERT INTO `quest_greeting` VALUES (4453, 0, 'Be careful where you put that foot of yours, $g sir : ma\'am;. We\'re not all blessed with the lofty height of a $R.', NULL, NULL, NULL, NULL, NULL, 'Tenga cuidado donde pone ese pie suyo, $g señor : señora ;. No todos somos bendecidos con la elevada altura de un $R.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (2546, 0, 'Yarrr... ye best not be trifling with my time, matey!', NULL, NULL, NULL, NULL, NULL, 'Yarrr ... ¡Será mejor que no juegues con mi tiempo, amigo!', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (5770, 0, 'If we are to protect nature, then we must embrace its strengths.  And we must show this strength to those who would harm the land.', NULL, NULL, NULL, NULL, NULL, 'Si queremos proteger la naturaleza, debemos abrazar sus fortalezas. Y debemos mostrar esta fuerza a aquellos que dañarían la tierra.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (265, 0, 'I have sensed your coming for quite some time, $n.  It was written in the pattern of the stars.', NULL, NULL, NULL, NULL, NULL, 'Siento que vienes desde hace bastante tiempo, $n. Estaba escrito con el patrón de las estrellas.', NULL, 'Я знал, что ты придешь, $n. Звезды рассказали мне об этом.', 0, 0);
INSERT INTO `quest_greeting` VALUES (273, 0, 'Keep the door closed, $c. Never know when the Dark Riders will be passing through again.', NULL, NULL, NULL, NULL, NULL, 'Mantenga la puerta cerrada, $c. Nunca se sabe cuándo volverán a pasar los Jinetes Oscuros.', NULL, 'Держи дверь закрытой, $c. Никогда не знаешь, когда Темные всадники пройдут здесь снова.', 0, 0);
INSERT INTO `quest_greeting` VALUES (733, 0, 'You watch where you step around here, $Glad:lass;.  You might not be a part of our outfit, but that doesn\'t mean I won\'t take a cane to you if you fall out of line!', NULL, NULL, NULL, NULL, NULL, 'Fíjate por dónde pisas, $G muchacho: muchacha;. Puede que no seas parte de nuestro atuendo, ¡pero eso no significa que no te llevaré un bastón si te pasas de la raya!', NULL, 'Смотри куда ступаешь, $gпарень:девушка;. Возможно, ты и не являешься частью нашей группы, но это не означает что я не подам тебе трость, если ты упадешь.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1071, 0, 'If there\'s one thing that Rhag taught me it\'s that no assignment is a dull one. Protecting the Thandol Span should have been an easy task. But with the brunt of the army fighting alongside the Alliance, we were overwhelmed here and Dun Modr has fallen.', NULL, NULL, NULL, NULL, NULL, 'Si hay algo que Rhag me enseñó es que ninguna tarea es aburrida. Proteger el Lapso Thandol debería haber sido una tarea fácil. Pero con la peor parte del ejército luchando junto a la Alianza, nos sentimos abrumados aquí y Dun Modr ha caído.', NULL, 'Защита моста Тандола была не простой задачей. Мы сконцентрировали свои здесь, сражаясь за это место, но Дун Модр пал.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2263, 0, 'I hope you\'re here to work, $C. We have a lot to do and the Horde, the Syndicate and the Ogres aren\'t going to help us.', NULL, NULL, NULL, NULL, NULL, 'Espero que estés aquí para trabajar, $C. Tenemos mucho que hacer y la Horda, el Sindicato y los Ogros no nos ayudarán.', NULL, 'Надеюсь, $c, вы здесь для того чтобы поработать. Нам необходимо многое сделать, а Орда, Синдикат и Огры не помогут нам.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2276, 0, 'When I was first offered the title of Southshore Magistrate I was exalted to have earned such a commission so early in my career.$B$BBut now that I\'m here, I wonder if I\'d have been better off shuffling papers in Stormwind.', NULL, NULL, NULL, NULL, NULL, 'Cuando me ofrecieron por primera vez el título de Magistrado de Costa Sur, me enorgulleció haber ganado tal comisión tan temprano en mi carrera. $B$BPero ahora que estoy aquí, me pregunto si hubiera estado mejor barajando papeles. en Ventormenta.', NULL, 'Когда мне впервые предложили звание судьи Южнобережья, я был очень рад, что получил такой титул в самом начале своей карьеры.$B$BНо теперь, когда я здесь, я задаюсь вопросом, что было бы лучше, если бы я остался перебирать бумаги в Штормграде.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2700, 0, 'We at Refuge Pointe hold one of the few remaining patches of Stromgarde territory in the Arathi Highlands. And we\'re losing ground...$B$BIf you have words for me, then I hope they are good doings.', NULL, NULL, NULL, NULL, NULL, 'En Punto de Refugio tenemos uno de los pocos parches que quedan del territorio de Stromgarde en las Tierras Altas de Arathi. Y estamos perdiendo terreno ... $B$BSi tienes palabras para mí, espero que sean buenas obras.', NULL, 'Опорный Пункт одно из немногих мест оставшееся от былого величия Стромграда, здесь в Нагорье Арати. Но мы теряем эти земли...$B$BЕсли у вас есть вести для меня, то я надеюсь что они хорошие.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2713, 1, 'This wooden board holds roughly made wanted posters.', NULL, NULL, NULL, NULL, NULL, 'Esta tabla de madera contiene carteles de búsqueda hechos de gran envergadura.', NULL, 'На этой деревянной доске размещены различные объявления о розыске.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2981, 0, 'Hail, $c. In my years I have seen many eager tauren who wish to prove their worth to the tribe. It should not be forgotten that eagerness is no substitute for wisdom and experience.', NULL, NULL, NULL, NULL, NULL, 'Salve, $c. En mis años he visto a muchos tauren ansiosos que desean demostrar su valía a la tribu. No debe olvidarse que el entusiasmo no sustituye a la sabiduría y la experiencia.', NULL, 'Приветствую, $c. В свои годы мне доводилось видеть множество нетерпеливых тауренов, которые хотят доказать свою ценность племени. Но не следует забывать, что стремление не заменит мудрость и опыт.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2988, 0, 'The Outrunners\' duty is to ensure the safety of those who travel across the plains of Mulgore. Those that would threaten the safety of the tauren homeland risk punishment at our hands.', NULL, NULL, NULL, NULL, NULL, 'El deber de los Corredores es garantizar la seguridad de quienes viajan por las llanuras de Mulgore. Aquellos que amenacen la seguridad de la patria tauren corren el riesgo de ser castigados en nuestras manos.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (2993, 0, 'The land has been good to our people, $c. We must be thankful for our good fortune.', NULL, NULL, NULL, NULL, NULL, 'La tierra ha sido buena para nuestra gente, $c. Debemos estar agradecidos por nuestra buena fortuna.', NULL, 'Эта земля благосклонна к нашему народу, $c. Мы должны быть благодарны за нашу удачу.', 0, 0);
INSERT INTO `quest_greeting` VALUES (4794, 0, 'Researching in Theramore is an interesting job, but it\'s sure hard to find a soft bed in this town!', NULL, NULL, NULL, NULL, NULL, 'Investigar en Theramore es un trabajo interesante, ¡pero seguro que es difícil encontrar una cama blanda en esta ciudad!', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (186420, 1, 'This collection of scrolls contains various logistic and strategic information, as well as coded correspondences.', NULL, NULL, NULL, NULL, NULL, 'Esta colección de pergaminos contiene diversa información logística y estratégica, así como correspondencias codificadas.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (239, 0, 'Adventure from lands far and near $bMeeting with folks both odd and queer $bBut if of me a question you ask $bYou must first complete a simple task!', NULL, NULL, NULL, NULL, NULL, 'Aventura desde tierras lejanas y cercanas $bEncuentro con gente rara y extraña $bPero si de mí una pregunta me haces $b¡Primero debes completar una tarea simple!', NULL, 'Приключения в ближних и дальних землях$BВстреча со странными и не странными людьми$BНо если у тебя есть, на который ты хочешь знать ответ$BСперва нужно решить простую задачу!', 0, 0);
INSERT INTO `quest_greeting` VALUES (267, 0, 'Welcome to the town of Darkshire.  Clerk Daltry at your service.  Can I be of some assistance?', NULL, NULL, NULL, NULL, NULL, 'Bienvenido a la ciudad de Comarca Oscura. Secretario Daltry a su servicio. ¿Puedo ser de alguna ayuda?', NULL, 'Добро пожаловать в Темнолесье. Клерк Далтри к вашим услугам. Могу ли я чем-то помочь?', 0, 0);
INSERT INTO `quest_greeting` VALUES (272, 0, 'Hello, hello!  Welcome to my kitchen, $g sir : m\'lady;!  This is where all of the Scarlet Raven Tavern\'s finest delicacies are made.  Ah, just smell the wonderful aroma!', NULL, NULL, NULL, NULL, NULL, '¡Hola hola! Bienvenido a mi cocina, $g señor : mi señora ;! Aquí es donde se elaboran todas las delicias más finas de Taberna del Cuervo Escarlata. ¡Ah, solo huele el maravilloso aroma!', NULL, 'Привет, привет! Добро пожаловать на мою кухню, $gсэр:миледи;! Здесь вы найдете самые лучшие деликатесы таверны \"Алый ворон\". Ах, какой прекрасный аромат!', 0, 0);
INSERT INTO `quest_greeting` VALUES (278, 0, 'Hello, good $gsir:lady;.  Have a seat, and a meal if you\'re hungry.  Don\'t fret if I look busy with my needlework - I\'m listening to you...', NULL, NULL, NULL, NULL, NULL, 'Hola, $g buen señor : buena señora ;. Siéntese y coma si tiene hambre. No te preocupes si parezco ocupado con mi costura, te estoy escuchando ...', NULL, 'Здравствуйте, $gсэр:леди;. Присаживайтесь и если вы голодны, угощайтесь. Не обращайте внимания на мою занятость, я вас внимательно слушаю...', 0, 0);
INSERT INTO `quest_greeting` VALUES (288, 0, 'Huh?!?  Oh.  You don\'t look like a Defias thief...or a member of the Night Watch.  Take pity on a poor soul, will ya?', NULL, NULL, NULL, NULL, NULL, '¿¡¿Eh?!? Oh. No pareces un ladrón Defias ... o un miembro de la Guardia Nocturna. Ten piedad de una pobre alma, ¿quieres?', NULL, 'А?!? Ох, вы не похожи на одного из членов Братства Справедливости... или Ночного Дозора. Не пощадите ли бедную душу?', 0, 0);
INSERT INTO `quest_greeting` VALUES (289, 0, 'Eh?  Greetings, young $C.  You\'re a brave one to find your way here with all those wandering creatures about!$B$BWell now that you are here, maybe you can help an old hermit...', NULL, NULL, NULL, NULL, NULL, '¿Eh? Saludos, joven $C. ¡Eres valiente para encontrar tu camino aquí con todas esas criaturas errantes! $B$BBueno, ahora que estás aquí, tal vez puedas ayudar a un viejo ermitaño ...', NULL, 'А? Приветствую вас, молодой $c. Вы очень смелы, раз пришли сюда мимо всех этих существ!$B$BХорошо, раз вы здесь, может, поможете старому отшельнику...', 0, 0);
INSERT INTO `quest_greeting` VALUES (294, 0, 'Hail, traveler.  My eyesight may be poor but I can sense the footsteps of a $c from a mile away.  For years I defended Stormwind with pride but once my eyes failed me, I was forced to retire.', NULL, NULL, NULL, NULL, NULL, 'Salve, viajero. Mi vista puede ser pobre, pero puedo sentir los pasos de un $c a una milla de distancia. Durante años defendí Ventormenta con orgullo, pero una vez que mis ojos me fallaron, me vi obligado a retirarme.', NULL, 'Приветствую тебя, искатель приключений. Мое зрение уже не так хорошо, как было раньше, но я могу за милю услышать шаги $c. В течение долго времени я стоял на страже Штормграда, но как мое зрение подвело меня, я был вынужден уйти в отставку.', 0, 0);
INSERT INTO `quest_greeting` VALUES (313, 0, 'Welcome to the Tower of Azora, young $C.  I am Theocritus.$B$BDo you have business with me?  Or...do I have business with you, perhaps?', NULL, NULL, NULL, NULL, NULL, 'Bienvenido a la Torre de Azora, joven $C. Yo soy Teócrito. $B$B¿Tiene negocios conmigo? O ... ¿quizás tengo negocios contigo?', NULL, 'Добро пожаловать в Башню Азоры, молодой $c. Я Теокрит.$B$BУ тебя есть ко мне какие-то вопросы? Или... у тебя есть вопросы к себе?', 0, 0);
INSERT INTO `quest_greeting` VALUES (341, 0, 'I don\'t have much time for idle talk, $N.  I\'ve got to get this bridge rebuilt before the rains come.  I\'ve finished every project on-time and under budget and I\'m not about to start slipping now.', NULL, NULL, NULL, NULL, NULL, 'No tengo mucho tiempo para charlas ociosas, $N. Tengo que reconstruir este puente antes de que lleguen las lluvias. Terminé todos los proyectos a tiempo y por debajo del presupuesto y no voy a empezar a perderme ahora.', NULL, 'У меня нет времени на разговоры, $n. Мне нужно разобраться с этим мостом до того как пойдет дождь. Я каждый проект заканчивал вовремя, и не собираюсь прокалываться сейчас.', 0, 0);
INSERT INTO `quest_greeting` VALUES (381, 0, 'Well met, $C.  If you\'re here for business, then get yourself a brew and we\'ll have ourselves a talk.', NULL, NULL, NULL, NULL, NULL, 'Buen conocido, $C. Si estás aquí por negocios, tómate una cerveza y hablaremos nosotros mismos.', NULL, 'Приветствую, $c. Если вы здесь по делам, тогда берите себе настойку и обсудим ваши дела.', 0, 0);
INSERT INTO `quest_greeting` VALUES (382, 0, 'I don\'t have time to chat, citizen, but if you\'re willing to give us a hand against the orcs, then I\'ll find a use for you.', NULL, NULL, NULL, NULL, NULL, 'No tengo tiempo para charlar, ciudadano, pero si estás dispuesto a echarnos una mano contra los orcos, te encontraré una utilidad.', NULL, 'У меня нет времени на болтовню. Но если ты $Gготов:готова; протянуть нам руку помощи в сражении против орков, тогда я найду тебе применение.', 0, 0);
INSERT INTO `quest_greeting` VALUES (415, 0, 'Hey $Gbuddy:ma\'am;, do you think you could give me a hand with something?  I\'m really in dire straits here...', NULL, NULL, NULL, NULL, NULL, 'Hola $G amigo : señora; ¿cree que podría echarme una mano con algo? Estoy realmente en una situación desesperada aquí ...', NULL, 'Эй $gприятель:мэм;, думаете, вы сможете мне что-то дать? Я и вправду в ужасном положении здесь...', 0, 0);
INSERT INTO `quest_greeting` VALUES (464, 0, 'Hail, $C.  Ill times these are, my friend, for our town is besieged!  The Blackrock Orcs attack from Stonewatch Keep, the Shadowhides loom over the Tower of Ilgalar, and the Redridge Gnoll Pack gathers strength.  I hope you\'re not here for a holiday...', NULL, NULL, NULL, NULL, NULL, 'Salve, $C. ¡Son tiempos malos, amigo mío, porque nuestra ciudad está sitiada! Los Orcos Roca Negra atacan desde Torre de la Guardia de Piedra, los Pellejos de Sombra se ciernen sobre la Torre de Ilgalar, y Paquete Gnoll Crestagrana gana fuerza. Espero que no estés aquí de vacaciones ...', NULL, 'Приветствую тебя, $c. Сейчас настали плохие времена для нашего города, друг мой. Орки ведут свои атаки со стороны крепости Каменной Стражи, Темношкуры маячат у башни Илгалара, а гноллы Красногорья собираются с силами. Надеюсь, ты здесь не для отдыха...', 0, 0);
INSERT INTO `quest_greeting` VALUES (469, 0, 'Greetings, $c.  If you\'re a friend of Colonel Kurzen then I\'ll have you cut down where you stand! but if you\'ve come to aid us, then lend an ear...', NULL, NULL, NULL, NULL, NULL, 'Saludos, $c. Si eres amigo del coronel Kurzen, ¡haré que te corten donde estás parado! pero si has venido a ayudarnos, presta atención ...', NULL, 'Приветствую, $c. Если ты $Gодин:одна; из приспешников полковника Курцена, тогда стой где стоишь! Но если ты здесь чтобы помочь нам, тогда я слушаю...', 0, 0);
INSERT INTO `quest_greeting` VALUES (633, 0, 'It\'s dark times that have come, $c... All too soon will we lose everything... When the Light will forsake all but those who truly walk under the Light.', NULL, NULL, NULL, NULL, NULL, 'Han llegado tiempos oscuros, $c ... Demasiado pronto lo perderemos todo ... Cuando la Luz abandonará a todos menos a aquellos que verdaderamente caminan bajo la Luz.', NULL, 'Пришли темные времена, $c... Скоро мы все потеряем... Свет покинет всех.', 0, 0);
INSERT INTO `quest_greeting` VALUES (656, 0, 'There were thieves everywhere! $b$bIt was horrible.  The cave came down on us.  I think the mining company is all dead, including my brother, the Foreman.', NULL, NULL, NULL, NULL, NULL, '¡Había ladrones por todas partes! $b$bFue horrible. La cueva cayó sobre nosotros. Creo que la empresa minera está muerta, incluido mi hermano, el Capataz.', NULL, 'Бандиты были всюду!$B$BЭто было ужасно. Пещера обвалилась на нас. Думаю, вся добывающая компания мертва, включая моего брата, Штейгера.', 0, 0);
INSERT INTO `quest_greeting` VALUES (663, 0, 'The Carevin family fights for victory under the Light. My duty under the Light is to give my life in their battle against against the undead. Master Carevin has tasked me with the extermination of the vile worgen in Duskwood. Perhaps you would assit me?', NULL, NULL, NULL, NULL, NULL, 'La familia Carevin lucha por la victoria bajo la Luz. Mi deber bajo la Luz es dar mi vida en su batalla contra los no muertos. El maestro Carevin me ha encomendado la tarea de exterminar a los viles huargen en Bosque del Ocaso. ¿Quizás me ayudarías?', NULL, 'Семья Карвин сражается во имя Света. Моя служба Свету дает мне сил в сражении против нежити. Мастер Карвин поручил мне уничтожить мерзких воргенов в Сумеречном лесу. Может, ты мне поможешь?', 0, 0);
INSERT INTO `quest_greeting` VALUES (1105, 0, 'You know, I always wanted to be a Prospector, but I was born with a head for numbers and the Guild decided I would be best suited to keep the books! Studying, studying, every day of my youth...', NULL, NULL, NULL, NULL, NULL, 'Sabes, siempre quise ser Prospector, pero nací con cabeza para los números y el Gremio decidió que yo sería el más adecuado para llevar los libros. Estudiar, estudiar, todos los días de mi juventud ...', NULL, 'Знаешь, мне всегда хотелось стать геологом, но моя голова с рождения все очень хорошо запоминала и Гильдия решила повесить на меня ответственность за книги! Изучение, изучение, каждый день изучение...', 0, 0);
INSERT INTO `quest_greeting` VALUES (1139, 0, 'Well hello there, citizen. The name\'s Bluntnose, Magistrate Bluntnose, to be precise. I\'m charged with overseeing the well-being of Thelsamar, and believe you me, we could always use another strong set of arms around here!', NULL, NULL, NULL, NULL, NULL, 'Bueno, hola, ciudadano. El nombre es Narizroma, Magistrado Narizroma, para ser precisos. Estoy encargado de supervisar el bienestar de Thelsamar, y créanme, ¡siempre podríamos usar otro par de brazos fuertes por aquí!', NULL, 'Привет. Меня зовут Тупонос, мировой судья Тупонос, если быть точнее. Мне поручено следить за благополучием Телсамара.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1141, 0, 'If you\'re here for the food, then welcome!  You won\'t find finer dining in all of Stormwind...or Azeroth!$B$BIf you\'re here on other matters, then please be brief.  I have a dozen dishes in preparation, and must care for each.', NULL, NULL, NULL, NULL, NULL, 'Si estás aquí por la comida, ¡bienvenido! No encontrarás mejores comidas en todo Ventormenta ... ¡o Azeroth!$B$BSi estás aquí por otros asuntos, por favor, sé breve. Tengo una docena de platos en preparación y debo cuidar de cada uno.', NULL, 'Если вы здесь ради еды, тогда добро пожаловать! Вы не найдете еду лучше во всем Штормграде... или Азероте!$B$BЕсли вы здесь по другим вопросам, тогда, пожалуйста, давайте быстрее. У меня готовится очень много блюд и мне нужно позаботиться о каждом из них.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1239, 0, 'If you\'re willing to endure tales that will shiver your timbers and sog your skivvies, then get yourself a drink and sit for a spell...', NULL, NULL, NULL, NULL, NULL, 'Si estás dispuesto a soportar cuentos que te hagan temblar las vigas y te empapen las botas, tómate un trago y siéntate por un rato ...', NULL, 'Если вы готовы выслушать дюжину рассказов, тогда присаживайтесь перед заклинением...', 1, 0);
INSERT INTO `quest_greeting` VALUES (1254, 0, 'Troggs! I swear the gods put them in this land only to torment me! Four inches deeper into the mines, then two feet back from the troggs!', NULL, NULL, NULL, NULL, NULL, '¡Troggs! ¡Juro que los dioses los pusieron en esta tierra solo para atormentarme! ¡Cuatro pulgadas más adentro de las minas, luego dos pies atrás de los troggs!', NULL, 'Трогги! Клянусь, сами боги разместили их здесь, чтобы досаждать мне!', 0, 0);
INSERT INTO `quest_greeting` VALUES (1267, 0, 'Welcome to the Thunderbrew Distillery, founded by dear ol\' pappy, Arkilus Thunderbrew.  I\'ve been keeping the place running ever since my older brother, Grimbooze, disappeared in a drunken haze a few harvests ago.', NULL, NULL, NULL, NULL, NULL, 'Bienvenido a la destilería Brebajetrueno, fundada por el querido papá, Arkilus Brebajetrueno. He mantenido el lugar en funcionamiento desde que mi hermano mayor, Bebidasombría, desapareció en una neblina borracha hace algunas cosechas.', NULL, 'Добро пожаловать в нашу таверну! Я управляю этим местом с тех пор, как мой брат Мрачнобух исчез в пьяном кураже несколько урожаев назад.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1344, 0, 'Although we\'re trudging through a slow period at these ruins, I\'m confident it won\'t last long.  But in the meantime, I could use someone like you.  Would you like to aid the Dwarven Explorers\' Guild?', NULL, NULL, NULL, NULL, NULL, 'Aunque estamos atravesando un período lento en estas ruinas, estoy seguro de que no durará mucho. Pero mientras tanto, me vendría bien alguien como tú. ¿Te gustaría ayudar al gremio de exploradores enanos?', NULL, 'Мы уже долго возимся с этими руинами, но, надеюсь, это не продлится долго. Тем временем, можно было бы использовать кого-то вроде тебя. Не желаешь помочь Лиге исследователей?', 0, 0);
INSERT INTO `quest_greeting` VALUES (1356, 0, 'I\'m in the middle of a very important task.  Prospector business.  Unless you have something equally important to say, which I doubt, then you\'ll have to excuse me.', NULL, NULL, NULL, NULL, NULL, 'Estoy en medio de una tarea muy importante. Negocio de prospector. A menos que tenga algo igualmente importante que decir, lo cual dudo, tendrá que disculparme.', NULL, 'У меня сейчас очень важное задание. Если у вас есть что-то очень срочное для меня, о чем я очень сомневаюсь, тогда, давайте поговорим.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1440, 0, 'You\'ll not find a greater cache of knowledge than in the Royal Library of Stormwind!', NULL, NULL, NULL, NULL, NULL, '¡No encontrarás un alijo de conocimientos más grande que en la Biblioteca Real de Ventormenta!', NULL, 'Вы нигде не найдете знаний больше, чем в Королевской библиотеке!', 1, 0);
INSERT INTO `quest_greeting` VALUES (1646, 0, 'Greetings, I am Baros Alexston, City Architect of Stormwind.', NULL, NULL, NULL, NULL, NULL, 'Saludos, soy Baros Alexston, arquitecto de la ciudad de Ventormenta.', NULL, 'Приветствую. Я Барос Алекстон, городской архитектор Штормграда.', 0, 0);
INSERT INTO `quest_greeting` VALUES (1719, 0, 'Over here, you worthless...! If you want to do something useful, listen quick!', NULL, NULL, NULL, NULL, NULL, '¡Por aquí, inútil ...! Si quieres hacer algo útil, ¡escucha rápido!', NULL, 'Здесь ты $Gбесполезен:бесполезна;... ! Если ты действительно хочешь сделать что-то полезное, тогда слушай внимательно!', 0, 0);
INSERT INTO `quest_greeting` VALUES (1748, 0, 'I am Bolvar Fordragon, Highlord of Stormwind.', NULL, NULL, NULL, NULL, NULL, 'Soy Bolvar para el dragón, alto señor de Ventormenta.', NULL, 'Я Болвар Фордрагон, верховный лорд Штормграда.', 66, 0);
INSERT INTO `quest_greeting` VALUES (1977, 0, 'I was bred and educated for public service. A representative of the people. My skill was not in arms or crafts, but in words and persuasion.', NULL, NULL, NULL, NULL, NULL, 'Fui criado y educado para el servicio público. Un representante del pueblo. Mi habilidad no estaba en las armas ni en la artesanía, sino en las palabras y la persuasión.', NULL, 'Меня обучали служить обществу. Быть представителем народа. Мои навыки это не умение обращаться с оружием или в ремесле, а иметь подходящие слова и умение убеждать.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2092, 0, 'Siege engines are the pride of every pilot!', NULL, NULL, NULL, NULL, NULL, '¡Las máquinas de asedio son el orgullo de todo piloto!', NULL, 'Осадные машины – гордость каждого пилота!', 0, 0);
INSERT INTO `quest_greeting` VALUES (2094, 0, 'Greetings, $c. I\'m in a bit of a pinch right now, running very low on hides.', NULL, NULL, NULL, NULL, NULL, 'Saludos, $c. Estoy en un pequeño apuro en este momento, me estoy quedando muy bajo en pieles.', NULL, 'Приветствую вас, $c. Мы сейчас находимся в затруднительном положении, у нас очень мало шкур.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2785, 0, 'Back away!  Stay back!  I have a pack full of blastpowder and I\'m not afraid to use it!  I\'ll blow us all away!$B$BOh, never mind.  I thought you were someone else....', NULL, NULL, NULL, NULL, NULL, '¡Retroceder! ¡Quedarse atrás! ¡Tengo un paquete lleno de pólvora y no tengo miedo de usarlo! ¡Los dejaré boquiabiertos a todos! $B$BOh, no importa. Pensé que eras otra persona ...', NULL, 'Назад! У меня в руках взрывчатка наполненная порохом, и я не побоюсь ее использовать! Я убью нас всех!$B$BОх, не обращай внимания. Я думал, что это кто-то другой...', 0, 0);
INSERT INTO `quest_greeting` VALUES (2786, 0, 'Welcome to Bonegrip\'s Runes and Dooms, $c.  You may look, but do not touch.$B$BSome of the knowledge here is not meant for the...uninitiated.', NULL, NULL, NULL, NULL, NULL, 'Bienvenido a Runas y Condenados de Bonegrip, $c. Puede mirar, pero no tocar. $B$BParte del conocimiento aquí no está destinado a ... no iniciados.', NULL, 'Добро пожаловать в лавку Костохвата, $c. Вы можете смотреть, но ничего не трогайте.$B$BНекоторые из знаний, не предназначены для... непосвященных.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2860, 0, 'It was quite a departure, let me tell you, $c. We were grabbing whatever wasn\'t nailed down or could be removed quickly. We\'re a little spare on supplies because of it.', NULL, NULL, NULL, NULL, NULL, 'Fue una gran diferencia, déjame decirte, $c. Estábamos agarrando todo lo que no estaba clavado o podía quitarse rápidamente. Somos un poco libres de suministros por eso.', NULL, 'Это было довольно неплохое отступление я вам скажу, $c. Мы хватали все, что можно было унести, и от этого наши запасы не так велики.', 0, 0);
INSERT INTO `quest_greeting` VALUES (2910, 0, 'Bastards came right at us at night, after we\'d gotten a few drinks in us. Otherwise, we could\'ve taken \'em, count on it.$B$BEveryone\'s dead now... except a few of us.', NULL, NULL, NULL, NULL, NULL, 'Los bastardos vinieron directamente a nosotros por la noche, después de que nos hubiéramos tomado unas copas. De lo contrario, podríamos haberlos tomado, cuenta con ello. $B$BTodos están muertos ahora ... excepto algunos de nosotros.', NULL, 'Они пришли ночью, как раз после того, как мы употребили несколько крепких напитков. В противном случае, мы бы схватили их.$B$BТеперь все мертвы... кроме нескольких из нас.', 1, 0);
INSERT INTO `quest_greeting` VALUES (2920, 0, 'Hey there, $N.$B$BLotwil\'s not the most perceptive boss I\'ve had. He actually gets really involved with his work. So much so that sometimes his servants don\'t eat, or get paid.$B$B$B$BBut that doesn\'t mean you should suffer.', NULL, NULL, NULL, NULL, NULL, 'Hola, $N.$B$BLotwil no es el jefe más perspicaz que he tenido. De hecho, se involucra mucho en su trabajo. Tanto es así que a veces sus sirvientes no comen o no les pagan. $B$B$B$BPero eso no significa que debas sufrir.', NULL, 'Привет, $n.$B$BЛотвитль не самый лучший босс, который у меня когда-то был. Он очень погружен в свою работу, настолько, что иногда его прислужники остаются голодными или без оплаты.$B$B$B$B*Люсьен хмуро смотрит на Лотвитля.*', 1, 0);
INSERT INTO `quest_greeting` VALUES (3663, 0, 'Good day, $glad:lass;! Perhaps you could help me with some things that need to be taken care of.', NULL, NULL, NULL, NULL, NULL, 'Buen día, $g muchacho: muchacha;! Quizás podrías ayudarme con algunas cosas que deben ser atendidas.', NULL, 'Доброго дня! Возможно, вы бы смогли мне помощь с некоторыми вещами, о которых необходимо позаботиться.', 0, 0);
INSERT INTO `quest_greeting` VALUES (3666, 0, 'Hmm... I can plug this wire in here and that will power the fizzletan gear, but then the hydrophlange will need an alternate power source... Maybe I can... Oh, hello! Hey, want to help me try a new invention?', NULL, NULL, NULL, NULL, NULL, 'Hmm ... Puedo enchufar este cable aquí y eso encenderá el equipo Bronceado, pero luego la Brida Hidráulica necesitará una fuente de energía alternativa ... Quizás pueda ... ¡Oh, hola! Oye, ¿quieres ayudarme a probar un nuevo invento?', NULL, 'Хм... я могу подключить этот провод сюда, и тогда механизм придет в действие, но тогда для гиро потребуется альтернативный источник питания... Возможно, я могу... О, привет! Не хочешь помочь мне с новым изобретением?', 0, 0);
INSERT INTO `quest_greeting` VALUES (4078, 0, 'Hello, friend. What can I do for you?', NULL, NULL, NULL, NULL, NULL, 'Hola amigo. ¿Qué puedo hacer por ti?', NULL, 'Приветствую, $gдруг:подруга;. Что я могу сделать для вас?', 6, 0);
INSERT INTO `quest_greeting` VALUES (4456, 0, 'No, Longears isn\'t my real name.  And I\'m not going to tell you what it is, so don\'t ask.', NULL, NULL, NULL, NULL, NULL, 'No, Orejas Largas no es mi nombre real. Y no les voy a decir qué es, así que no pregunten.', NULL, 'Нет, Длинноушка не мое настоящее имя. И я не сообщу тебе, что это означает, даже не спрашивай.', 0, 0);
INSERT INTO `quest_greeting` VALUES (4792, 0, 'Some people think the swamp\'s no good... no good, they say.', NULL, NULL, NULL, NULL, NULL, 'Algunas personas piensan que el pantano no es bueno ... no es bueno, dicen.', NULL, 'Некоторые говорят, что болота это не хорошо... ничего хорошего, говорят они.', 0, 0);
INSERT INTO `quest_greeting` VALUES (5396, 0, 'The Alliance has many stakes in Desolace, and our hold here is unstable.$B$BWill you help us?', NULL, NULL, NULL, NULL, NULL, 'La Alianza tiene muchas participaciones en Desolace, y nuestro control aquí es inestable. $B$B¿Nos ayudarán?', NULL, 'Альянс имеет много ставок здесь в Пустошах, и наша позиция здесь неустойчива.$B$BПоможете ли вы нам?', 0, 0);
INSERT INTO `quest_greeting` VALUES (5638, 0, 'I\'ve got a lot going on out here in Desolace, $N. Roetten wants us to pick up some reagents for one of our clients as well as fetch some of these lost items.$B$BSeein\' as you\'re here to help out, why don\'t we get started?', NULL, NULL, NULL, NULL, NULL, 'Tengo muchas cosas que hacer aquí en Desolace, $N. Roetten quiere que recojamos algunos reactivos para uno de nuestros clientes, así como algunos de estos artículos perdidos. $B$BYa que estás aquí para ayudar, ¿por qué no empezamos?', NULL, 'У меня много дел здесь в Пустошах, $n. Ройттен хочет, чтобы мы забрали некоторые реагенты для одного из наших клиентов, а также доставили несколько утраченных предметов.$B$BПохоже, что ты здесь чтобы помочь нам, так почему бы нам не начать?', 1, 0);
INSERT INTO `quest_greeting` VALUES (6031, 0, 'Some can\'t stand the heat of the Great Forge, but I think the heat is just right.  And it\'s the best place to do some serious smithwork.', NULL, NULL, NULL, NULL, NULL, 'Algunos no pueden soportar el calor de la Gran Fragua, pero creo que el calor es perfecto. Y es el mejor lugar para hacer un trabajo de herrería serio.', NULL, 'Некоторые не могут выдержать тот жар, исходящий от Великой Кузни, но я считаю, что с этим здесь все в порядке. Это лучшее место для того, чтобы в серьез заняться кузнечным делом.', 1, 0);
INSERT INTO `quest_greeting` VALUES (6179, 0, 'Many tests await a paladin of the Light, $N. Be assured, our paths will cross many times in the future if you remain passionate and hold to those virtues that we praise.', NULL, NULL, NULL, NULL, NULL, 'Muchas pruebas aguardan a un paladín de la Luz, $N. Tenga la seguridad de que nuestros caminos se cruzarán muchas veces en el futuro si permanece apasionado y se aferra a esas virtudes que alabamos.', NULL, 'Многие испытания ждут паладина Света, $n. Будьте уверены, в будущем, наши пути еще много раз пересекутся, если же вы все также останетесь верны своей страсти и не отбросите те качества, которые мы возвышаем.', 1, 0);
INSERT INTO `quest_greeting` VALUES (6569, 0, 'Where Troggs and Leper Gnomes roam stands our home - Gnomeregan.$B$BOur families lost, our homes displaced. Scattered.$B$BOh how I long for the days of carefree Gnomeregan life, but those days are no more. We must make our stand! We must save Gnomeregan!', NULL, NULL, NULL, NULL, NULL, 'Donde vagan los Troggs y los gnomos leprosos se encuentra nuestro hogar: Gnomeregan. $B$BNuestras familias perdidas, nuestros hogares desplazados. Dispersos. $B$BOh, cuánto anhelo los días de la vida despreocupada de Gnomeregan, pero esos días ya no existen. ¡Debemos mantenernos firmes! ¡Debemos salvar a Gnomeregan!', NULL, 'Там где обитают Трогги и лепрогномы, наш дом – Гномреган.$B$BНаши семьи потеряны, наш дом теперь теперь другой.$B$BОх, как хочется вернуться в те беззаботные дни жизни в Гномрегане, но этих дней больше нет. Мы должны укрепить нашу позицию! Мы должны вернуть Гномреган!', 0, 0);
INSERT INTO `quest_greeting` VALUES (6579, 0, 'For Gnomeregan!', NULL, NULL, NULL, NULL, NULL, '¡Por Gnomeregan!', NULL, 'За Гномреган!', 0, 0);
INSERT INTO `quest_greeting` VALUES (9081, 0, 'I never miss...', NULL, NULL, NULL, NULL, NULL, 'Nunca echo de menos ...', NULL, 'Я никогда не промахиваюсь...', 25, 0);
INSERT INTO `quest_greeting` VALUES (9177, 0, 'Stand at attention, soldier!$B$BWINKY! SOUND OFF!', NULL, NULL, NULL, NULL, NULL, '¡Párate en atención, soldado! $B$B¡WINKY! ¡SONIDO APAGADO!', NULL, 'Будь начеку, солдат!$B$BТИХО!', 5, 0);
INSERT INTO `quest_greeting` VALUES (9562, 0, 'Greetings, $R.', NULL, NULL, NULL, NULL, NULL, 'Saludos, $r.', NULL, 'Приветствую вас, $r.', 2, 0);
INSERT INTO `quest_greeting` VALUES (10260, 0, 'Welcome to Kibler\'s Exotic Pets! How can you help me today??', NULL, NULL, NULL, NULL, NULL, '¡Bienvenido a las mascotas exóticas de Kibler! ¿Cómo puedes ayudarme hoy?', NULL, 'Добро пожаловать в экзотический питомник Киблера! Чем вы можете мне сегодня помочь?', 5, 0);
INSERT INTO `quest_greeting` VALUES (3848, 0, 'The balance of nature is a delicate one, and easily tipped.  Are you brave enough to make things right?', NULL, NULL, NULL, NULL, NULL, 'El equilibrio de la naturaleza es delicado y fácil de inclinar. ¿Eres lo suficientemente valiente para hacer las cosas bien?', NULL, 'Природный баланс очень хрупок. Но достаточно ли вы храбры, чтобы все исправить?', 1, 0);
INSERT INTO `quest_greeting` VALUES (1952, 0, 'Hello, $C.  If you\'re here, then you must know that Silverpine is saturated with our enemies.  To survive, the Forsaken must drive them back!', NULL, NULL, NULL, NULL, NULL, 'Hola, $C. Si estás aquí, debes saber que los Argénteos están saturados de enemigos. ¡Para sobrevivir, los Renegados deben hacerlos retroceder!', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (10321, 0, '<Emberstrife acknowledges your presence.>', NULL, NULL, NULL, NULL, NULL, '<La lucha de las ascuas reconoce tu presencia.>', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (11596, 0, 'My business plan never accounted for housing giant kodos... maybe I should have gone into the underwater basket weaving business instead.', NULL, NULL, NULL, NULL, NULL, 'Mi plan de negocios nunca tuvo en cuenta la vivienda de kodos gigantes ... tal vez debería haberme dedicado al negocio del tejido de cestas bajo el agua.', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (7777, 0, 'The Gordunni Ogres encroach upon our lands.  We send as many as are willing to face them in the desecrated ruins of Feralas.', NULL, NULL, NULL, NULL, NULL, 'Los ogros Gordunni invaden nuestras tierras. Enviamos a todos los que estén dispuestos a enfrentarlos en las ruinas profanadas de Feralas.', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (16361, 0, 'The Lich King has brought war against us from the frozen north, and only we of the Argent Dawn stand in his way.', NULL, NULL, NULL, NULL, NULL, 'El Rey Exánime nos ha traído la guerra desde el norte helado, y solo nosotros, los del Alba Argenta, nos interponemos en su camino.', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (16478, 0, 'Good day to you, citizen. Have you come to aid us against the Scourge?', NULL, NULL, NULL, NULL, NULL, 'Buen día, ciudadano. ¿Has venido a ayudarnos contra la Plaga?', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (16786, 0, 'Greetings, $n. If you bring me necrotic stones from the undead invaders, I can give you access to the stores of the Argent Dawn.', NULL, NULL, NULL, NULL, NULL, 'Saludos, $n. Si me traes piedras necróticas de los invasores no muertos, puedo darte acceso a las tiendas del Alba Argenta.', NULL, NULL, 66, 0);
INSERT INTO `quest_greeting` VALUES (16788, 0, 'Greetings, $c. I am the Flamekeeper. During the Midsummer Fire Festival, it is my duty to keep this fire beside me burning brightly. It is an honor to be selected for such a task; I fill it gladly.$b$b How can I help you?', NULL, NULL, NULL, NULL, NULL, 'Saludos, $c. Yo soy el guardián de las llamas. Durante el Festival del Fuego del Solsticio de Verano, es mi deber mantener este fuego a mi lado ardiendo brillantemente. Es un honor ser seleccionado para tal tarea; Lo lleno con mucho gusto. $B$b¿Cómo puedo ayudarte?', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (1938, 0, 'The Kirin Tor did not heed my warnings!  The Alliance is a sham.  Arugal is a wreckless fool.', NULL, NULL, NULL, NULL, NULL, '¡El Kirin Tor no hizo caso de mis advertencias! La Alianza es una farsa. Arugal es un tonto implacable.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (2055, 0, 'The Royal Apothecary Society shall heed The Dark Lady\'s call to uncover the New Plague and drive Arthas and his heathen Scourge Army from the world once and for all.', NULL, NULL, NULL, NULL, NULL, 'La Sociedad Real de Boticarios prestará atención al llamado de la Dama Oscura para descubrir la Nueva Plaga y expulsar a Arthas y su ejército pagano de la Plaga del mundo de una vez por todas.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (2229, 0, 'To think, the place the Warchief was born and raised lies so close.', NULL, NULL, NULL, NULL, NULL, 'Pensar que el lugar donde nació y se crió el Jefe de Guerra está tan cerca.', NULL, NULL, 0, 0);
INSERT INTO `quest_greeting` VALUES (4454, 0, 'Aha!  Did you see that!  I think this new auto-spanner is going to do just the trick for my new influx manifold design.', NULL, NULL, NULL, NULL, NULL, '¡Ajá! ¡Viste eso! Creo que esta nueva llave automática va a hacer el truco para mi nuevo diseño de colector de afluencia.', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (11259, 0, 'Desolace is not such a bad place, if you don\'t mind the constant harassments from the centaurs.', NULL, NULL, NULL, NULL, NULL, '<La lucha de las ascuas reconoce tu presencia.>', NULL, NULL, 1, 0);
INSERT INTO `quest_greeting` VALUES (0, 0, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0);

SET FOREIGN_KEY_CHECKS = 1;
